spring:
  datasource:
    url: "jdbc:mysql://192.168.1.200:3307/rehabilitation?serverTimezone=
    Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false"
    username: root
    password: root
  redis:
    host: 192.168.1.200
    port: 6379
    database: 1
server:
  port: 8081
customize:
  updateLog: false
  swagger: true
  file-base-path: C:\zfei\data\